//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Project.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Events
    {
        public int EventID { get; set; }
        public int ClassID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public System.DateTime Start { get; set; }

        //public string Start { get; set; }

        //public string Start2 { get { return Start2; } set { Start2 = Start.ToString("MM/dd/yyyy"); } }

        public Nullable<System.DateTime> End { get; set; }
        public string ThemeColor { get; set; }
        public bool IsFullDay { get; set; }
    
        public virtual School_Class School_Class { get; set; }
    }
}
