//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Grades
    {
        public int GradeID { get; set; }
        public double Ocena { get; set; }
        public int TeacherID { get; set; }
        public int StudentID { get; set; }
        public string Uwagi { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
